"""Pixels to deck millimetres.

This module decides where the OT is told to go, on a machine with no endstops
where a wrong coordinate is a crash that every software signal reports as
success. So the tests care less about "does it fit" than about "does it refuse
when it should".

Correspondences are generated by applying a known homography, so the recovered
transform can be checked against the one used to make the data. No camera and no
OT required.
"""
from __future__ import annotations

import numpy as np
import pytest

from core.calibration.deck_homography import (
    MAX_RMS_MM,
    MIN_POINTS_FOR_TRUST,
    correction_mm,
    fit_deck_homography,
)

# A plausible overhead view: deck roughly 200x150 mm seen by a 640x480 camera,
# with perspective, so the mapping is genuinely projective and not a similarity.
TRUE_H = np.array([
    [0.32, 0.02, -18.0],
    [-0.015, 0.31, -12.0],
    [0.00022, 0.00013, 1.0],
])


def to_deck(H: np.ndarray, uv) -> np.ndarray:
    q = H @ np.array([uv[0], uv[1], 1.0])
    return q[:2] / q[2]


def make_pairs(uvs, H=TRUE_H, noise_mm=0.0, seed=0):
    rng = np.random.default_rng(seed)
    img, deck = [], []
    for uv in uvs:
        img.append(list(uv))
        pt = to_deck(H, uv)
        if noise_mm:
            pt = pt + rng.normal(0, noise_mm, size=2)
        deck.append(pt.tolist())
    return img, deck


GRID = [(120, 100), (500, 110), (130, 380), (510, 370), (320, 240), (200, 300), (430, 180)]


def test_recovers_a_known_homography():
    img, deck = make_pairs(GRID)
    fit = fit_deck_homography(img, deck)
    assert fit.trustworthy, fit.why_not_trustworthy()
    assert fit.rms_mm < 1e-6
    # And it maps a point that was not in the fit data.
    held_out = (280, 200)
    assert fit.to_deck(held_out) == pytest.approx(to_deck(TRUE_H, held_out), abs=1e-6)


def test_survives_realistic_detection_noise():
    """Half a millimetre of labelling noise must still give a usable fit."""
    img, deck = make_pairs(GRID, noise_mm=0.5, seed=3)
    fit = fit_deck_homography(img, deck)
    assert fit.trustworthy, fit.why_not_trustworthy()
    assert fit.rms_mm < MAX_RMS_MM


def test_four_points_fit_but_are_not_trusted():
    """The important refusal.

    Four correspondences determine a homography exactly, so the residual is zero
    even when the correspondences are wrong. A clean fit on four points is not
    evidence, and treating it as evidence is how a mislabelled tag becomes a
    crash.
    """
    img, deck = make_pairs(GRID[:4])
    fit = fit_deck_homography(img, deck)
    assert fit.rms_mm < 1e-6          # fits perfectly
    assert not fit.trustworthy        # and is still not trusted
    assert str(MIN_POINTS_FOR_TRUST) in fit.why_not_trustworthy()


def test_a_mislabelled_correspondence_is_caught():
    """With enough points, a swapped pair shows up as residual rather than hiding."""
    img, deck = make_pairs(GRID)
    deck[2], deck[5] = deck[5], deck[2]
    fit = fit_deck_homography(img, deck)
    assert not fit.trustworthy
    assert fit.rms_mm > MAX_RMS_MM
    assert "RMS" in fit.why_not_trustworthy()


def test_collinear_points_are_refused():
    """Cannot be caught by the residual, so it is checked directly."""
    line = [(100, 100), (200, 150), (300, 200), (400, 250), (500, 300)]
    img, deck = make_pairs(line)
    with pytest.raises(ValueError, match="collinear"):
        fit_deck_homography(img, deck)


def test_too_few_points_is_refused():
    img, deck = make_pairs(GRID[:3])
    with pytest.raises(ValueError, match="at least 4"):
        fit_deck_homography(img, deck)


def test_unpaired_input_is_refused():
    img, deck = make_pairs(GRID)
    with pytest.raises(ValueError, match="paired"):
        fit_deck_homography(img, deck[:-1])


def test_correction_is_computed_on_the_deck_not_in_pixels():
    """The reason corrections are not a pixels-times-scale calculation.

    A homography is not a uniform scaling, so the same pixel offset is a
    different number of millimetres depending on where in the frame it happens.
    This asserts that difference is real, which is what makes a single
    mm-per-pixel factor wrong everywhere but one point.
    """
    img, deck = make_pairs(GRID)
    fit = fit_deck_homography(img, deck)

    near = correction_mm(fit, (150, 130), (170, 130))     # 20 px near one corner
    far = correction_mm(fit, (480, 350), (500, 350))      # 20 px near the other
    assert np.linalg.norm(near) != pytest.approx(np.linalg.norm(far), rel=0.02)


def test_correction_closes_the_error_it_measures():
    """The property the servo loop depends on."""
    img, deck = make_pairs(GRID)
    fit = fit_deck_homography(img, deck)

    observed, target = (300, 260), (340, 210)
    delta = correction_mm(fit, observed, target)
    # Applying the correction to the observed deck position lands on the target.
    assert fit.to_deck(observed) + delta == pytest.approx(fit.to_deck(target), abs=1e-6)


def test_a_horizon_point_raises_rather_than_returning_a_huge_number():
    """A point off the fitted plane has no deck coordinate.

    Returning a very large number instead would look like a reachable target,
    and the OT would be commanded toward it.
    """
    img, deck = make_pairs(GRID)
    fit = fit_deck_homography(img, deck)
    # Solve for where the third row vanishes: H[2] . (u, v, 1) == 0
    a, b, c = fit.matrix[2]
    u = 10_000.0
    v = (-c - a * u) / b
    with pytest.raises(ValueError, match="horizon"):
        fit.to_deck((u, v))


def test_z_is_never_produced():
    """Height must come from the machine's own axis, never from this model."""
    img, deck = make_pairs(GRID)
    fit = fit_deck_homography(img, deck)
    assert fit.to_deck((320, 240)).shape == (2,)
    assert correction_mm(fit, (300, 200), (310, 210)).shape == (2,)
